name: pulpox_admin
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_platform_widgets: ^1.20.0
  get: ^4.6.1
  get_storage:
  # get_storage: ^2.0.3
  intl: ^0.17.0

  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.7
  firebase_crashlytics: ^2.8.10
  firebase_performance: ^0.8.3
  firebase_analytics: ^9.3.5
  firebase_storage: ^10.3.8
  firebase_messaging: ^13.0.1

  google_fonts: ^2.3.1
  eva_icons_flutter: ^3.0.2
  flutter_svg: ^0.22.0

  sign_in_with_apple: ^3.3.0
  # facebook_and_google_signin: ^0.0.5
  google_sign_in: ^5.0.0
  google_sign_in_web: ^0.10.1
  # flutter_login_facebook: ^1.4.1

  provider: ^5.0.0

  # validator for inputs
  form_field_validator: ^1.0.1
  # cached_network_image: ^1.1.1

  fl_chart: ^0.36.1
  # provider: ^5.0.0
  data_table_2: ^2.0.3
  percent_indicator: ^3.4.0
  flutter_staggered_grid_view: ^0.4.1
  # font_awesome_flutter: ^10.1.0

  dotted_border: ^2.0.0+1
  timeago: ^3.1.0
  # google_sign_in_web: ^0.10.1
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/300dpi_jurix_isotipo_350px.png"
  # adaptive_icon_backgroud: "dev_assets/300dpi_jurix_isotipo_350px.png"

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/raster/
    - assets/images/vector/
    - assets/
    - assets/jurixlogo/
    - assets/jurixlogo/300dpi/300dpi_jurix_isotipo_350px.png
    - assets/images/illustration-2.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
